#!zsh

if (( $# < 2 )); then
   print -u 2 -- "usage: $0 env_name path_to_dir"
   return 1
fi

local -a env_names=(
   path fpath manpath cdpath library_path ld_library_path cpath
)

local index=${env_names[(ie)$1]}
if (( $index <= $#env_names )); then
   local env_name=$env_names[$index]
else
   echo -u 2 -- "Not env_name: $1"
   return 1
fi

eval "$env_name=($2(N-/) \$$env_name)"
