#!/usr/bin/env zsh

if (( $# < 1 )); then
   print -u 2 -- "usage: $0 archived"
   return 1
fi

case $1 in
*.tar.gz | *.tgz)   tar xvf $* ;;
*.tar.xz)           tar xvf $* ;;
*.zip)              unzip -d ${1:t:r} $* ;;
*.lzh)              lha e $* ;;
*.tar.bz2 | *.tbz)  tar xvf $* ;;
*.tar.Z)            tar xvf $* ;;
*.gz)               gzip -d $* ;;
*.bz2)              bzip2 -dc $* ;;
*.Z)                uncompress $* ;;
*.tar)              tar xvf $* ;;
*.arj)              unarj $* ;;
*.7z)               7z x -o${1:t:r} $* ;;
*)                  echo "Unknown file type: $1" >&2
esac
