#!/usr/bin/env zsh

if (( $# < 1 )); then
   print -u 2 -- "usage: $0 archived"
   return 1
fi

case $1 in
*.tar.gz | *.tgz)   tar xzvf $1 ;;
*.tar.xz)           tar Jxvf $1 ;;
*.zip)              unzip -d ${1:t:r} $1 ;;
*.lzh)              lha e $1 ;;
*.tar.bz2 | *.tbz)  tar xjvf $1 ;;
*.tar.Z)            tar zxvf $1 ;;
*.gz)               gzip -d $1 ;;
*.bz2)              bzip2 -dc $1 ;;
*.Z)                uncompress $1 ;;
*.tar)              tar xvf $1 ;;
*.arj)              unarj $1 ;;
*.7z)               7z x -o${1:t:r} $1 ;;
*)                  echo "Unknown file type: $1" >&2
esac
