#!zsh

if (( $# < 1 )); then
   print -u 2 -- "usage: $0 zshfile [options]"
   return 1
fi

local src=$1; shift 1
local zwc=${src}.zwc

if [[ -f $src ]]; then
   if [[ ! -f $zwc || $src -nt $zwc ]]; then
      zcompile $src
   fi
   source $src $@
fi
